### ISSUE TITLE
Picture tag

### ISSUE THREAD

**Issue by robots4life** [aderaaij/wp-image-preload#4]
Does this plugin support the picture tag?

**Comment by aderaaij** [comment]
Hi @robots4life, no it doesn't. I haven't looked at this in a while but I believe I only include support for  srcset, images and background images. Shouldn't be too hard to figure out how to add `picture` support though. Pull requests are always welcome

edit: Right now, images from the text editor are only checked if they're in an `img` tag. They come with `srcset` by default, so that's supported. In the JavaScript file I only check for `img[data-src]`, and background images.

**Comment by robots4life** [comment]
Ah perhaps I misunderstand something.
 `srcset` is supported but `source` or `picture` is not?
Being fairly new to PHP perhaps you have some pointers I could follow to add support.
